### ISSUE TITLE
generate_presigned_url runs 27 times

### ISSUE THREAD

**Issue by opher50** [backblaze-b2-samples/b2-python-s3-sample#10]
Hey,

So I've been using your functions and for some unknown reason the get_presgined_url functions runs 27 times everytime I call it:
def get_object_presigned_url(key, expiration_seconds, b2):
    try:
        response = b2.meta.client.generate_presigned_url(ClientMethod='get_object',
                                                         ExpiresIn=expiration_seconds,
                                                         Params={
                                                                    'Bucket': bucket,
                                                                    'Key': key
                                                                } )
        print(response)
        return response
    except ClientError as ce:
        print('error', ce)

Any idea why would that happen?

**Comment by metadaddy** [comment]
Hi @opher50 - I see you closed the issue. I guess you figured it out?
